# Generated by Django 2.2.6 on 2019-11-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='author/image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['rec_date']},
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=5000)),
                ('image', models.FileField(upload_to='blogs/image')),
                ('crumb_image', models.FileField(upload_to='blogs/image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='stats.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='blogs/image')),
                ('name', models.CharField(max_length=500)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='stats.BlogPost')),
            ],
        ),
    ]
