# Generated by Django 2.2.6 on 2019-11-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20191108_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimages',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='crumb_image',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='BlogImages',
        ),
    ]
