# Generated by Django 2.2.6 on 2019-11-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20191112_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='url',
            field=models.CharField(default='test', max_length=400),
            preserve_default=False,
        ),
    ]
