# Generated by Django 2.1 on 2018-08-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0002_author_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=5000)),
                ('image', models.FileField(upload_to='blogs/image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='author.Author')),
            ],
        ),
    ]
