# Generated by Django 2.0.1 on 2018-10-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='crumb_image',
            field=models.FileField(default='test', upload_to='blogs/image'),
            preserve_default=False,
        ),
    ]
