# Generated by Django 2.0.1 on 2018-05-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='job_title',
            field=models.CharField(default='temp bio', max_length=100),
            preserve_default=False,
        ),
    ]
